### ISSUE TITLE
forEach without an array

### ISSUE THREAD

**Issue by harwalan** [thanhson1085/swagger-combined#1]
It looks like in your last check-in, something got broken.  Either the example config is off or the program is off.  On line 46 of app.js, it is doing a forEach on whatever is in route_match in the config.  route_match is not an array, so the line fails.

I fixed that and am able to get the code to run, but it still doesn't work.  I am getting a 404. 

This looks cool. I'd love to see it working.

**Comment by thanhson1085** [comment]
Thanks for your report. It should be `["/v2*"]` instead of `"/v2*"` in config/default.json.
I also update REAME file to guide run this app from source code and fix "absolute path" issue in my code.
It should work now. Please try again.

**Comment by thanhson1085** [comment]
Does it work for you now?
