### ISSUE TITLE
Swagger-Combined not working on Linux

### ISSUE THREAD

**Issue by olatom** [thanhson1085/swagger-combined#11]
First, I will say thanks for sparing time to provide this solution.
I had this app working on my mac laptop connecting to remote services i.e. it was combining docs from different micro services on a remote server.
I ran the following to ensure the relevant software was installed on the server.
node -v > v0.10.46
npm -v  > 1.3.6

 Now, I deployed the node.js app to that same remote server with the services and I was getting the following error;

ReferenceError: Promise is not defined
    at checkConfig (/home/olakunle/microservices-swagger-ui/routes/swagger.js:33:14)
    at genDocs (/home/olakunle.tomoloju/discr-microservices-swagger-ui/routes/swagger.js:64:10)
    at agent (/home/olakunle/microservices-swagger-ui/routes/app.js:49:24)
    at Layer.handle [as handle_request](/home/olakunle.tomoloju/discr-microservices-swagger-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/olakunle/microservices-swagger-ui/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/olakunle/microservices-swagger-ui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/olakunle/microservices-swagger-ui/node_modules/express/lib/router/layer.js:95:5)
    at /home/olakunle/microservices-swagger-ui/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/olakunle/microservices-swagger-ui/node_modules/express/lib/router/index.js:330:12)
    at next (/home/olakunle/microservices-swagger-ui/node_modules/express/lib/router/index.js:271:10)

I would love to use the docker, but the lack of docker instruction did not help!
I was trying to use the following docs:

https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

But, i notice you have a dockerfile and a dockershell, but i could not use that. I thought that will be ideal for running in the app on a linux VM.

**Comment by thanhson1085** [comment]
Swagger Combined work on NodeJS 4+. So please upgrade you nodejs. You can refer to link [https://sonnguyen.ws/update-npm-to-latest-version/](https://sonnguyen.ws/update-npm-to-latest-version/)

```
ENV NODE_VERSION=v4.2.2 NPM_VERSION=2.14.2
```

**Comment by olatom** [comment]
Good day Pal, I have been trying to crack this, but I have made little advances and new issues etc
1. Forgetting about Docker for a minute! After trying different download n install options, NVM (https://github.com/creationix/nvm#install-script) did it for me  . I was able to set up node version 6.0.6 AND npm version 3.10.3 on the remote unix box. I repeated the instruction in your read me. Then, I was able to view all the swagger docs for my microservices on a page.
   
   BUT the "Try it out" functionality to execute the endpoint is NOT working. This is because the microservice endpoint are on a different port and could even be on a different host. But, the "Try it out" attempts to use the same host:port-no as the swagger-combined home docs page. For instance, if one of my micro services is on http://x.x.x.7:1234/car/part and the swagger-combine home is http://x.x.x.7:1000/
   When, I test the endpoint in swagger the endpoint is requested on http://x.x.x.7:1000/car/part instead of http://x.x.x.7:1234/car/part.
2. Could you help with some instructions on how to set up the combined swagger in docker and deploy the docker-app to a remote VM. I did try running your Docker file following the following instructions https://nodejs.org/en/docs/guides/nodejs-docker-webapp/. I get stuck when I try creating a docker image ... I stalled at building a docker image i.e. $ docker build -t <your username>/node-web-app . 

I followed your post on:
https://www.npmjs.com/package/swagger-combined
i.e. Create the configuration file config/default.json and mount it to the container:

docker run -d -p 3000:3000 -v ./config/default.json:/build/config/local.json thanhson1085/swagger-combined

But, no luck ... I guess "thanhson1085/swagger-combined" is the image which I needed to be created.

I am very new to docker. So any help will be appreciated.
1.  But, my main target will be been able to test the endpoint from the swagger combined docs page. Thanks.

Thanks a lot for your support and keep up the good works.
