### ISSUE TITLE
Npm install fails v1.4.2

### ISSUE THREAD

**Issue by DaveStein** [thanhson1085/swagger-combined#13]
`fetchMetadata: ERR! registry error parsing json` 

Seems like dependency issue? Your package.json is fine

**Comment by thanhson1085** [comment]
You should clone source code and run `npm install`, should not install via `npm install swagger-combined`

**Comment by DaveStein** [comment]
Weird... I would have never run that second command. It's working fine now. I wonder if a dependency had a glitch yesterday.
