### ISSUE TITLE
stuck in "fetching resource list"

### ISSUE THREAD

**Issue by thiagobucca** [thanhson1085/swagger-combined#19]
Hello,

I'm having issues using swagger-combined, i have 2 microservices hosted on the same server, what changes is just the endpoint, something like this:

        {
           "docs": "https://myhost/service1/swagger/v1/swagger.json",
            "base_path": "myhost/service1/",
            "route_match": ["/api/service1*"] 
        },
        {
            "docs": "https://myhost/service2/swagger/v1/swagger.json",
            "base_path": "myhost/service2/",
            "route_match": ["/api/service2*"] 
        }

when i start the application, it get stuck in "fetching resource list", no error on browser's console.

any tips on this?

**Comment by thiagobucca** [comment]
managed to solve this by commenting the following line in index.js file:

`          // combines tags
              //  a.tags = (a.tags || []).concat(i.tags || []);`

**Comment by thanhson1085** [comment]
Thank you for using and testing Swagger Combined.
